config/routes.rb
Rails.application.routes.draw do
 
  

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'welcome#index'

    get 'signup'  => 'users#new'
    resources :users

    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/user_mailler/account_activation.html.erb
<h1>Made In Mada</h1>

<p>Bonjour <%= @user.username %>,</p>

<p>
Bienvenue ! Veuillez cliquer sur le lien ci-dessous pour activer votre compte:
</p>

<%= link_to "Activer", edit_account_activation_url(@user.activation_token, email: @user.email) %>

app/views/user_mailler/account_activation.text.erb
UserMailler#account_activation

Bonjour <%= @user.username %>,

Bienvenue. Veuillez cliquer sur le lien ci-dessous pour activer votre compte:

<%= edit_account_activation_url(@user.activation_token, email: @user.email) %>

app/views/user_mailler/password_reset.html.erb
<h1>R&eacute;initialisation de mot de passe</h1>

<p>
  Une demande a &eacute;t&eacute; faite pour r&eacute;initialiser  votre mot de passe. Pour ce faire, cliquez sur le lien ci-dessous
</p>

<%= link_to "reinitialiser mon mot de passe", edit_password_reset_url(@user.reset_token,
                                                                             email: @user.email) %>

<p>Ce lien expirera dans deux heures</p>  

<p>Si vous n'avez pas solicit&eacute; ce changement de mot de passe, veuillez s'il vous plait, ignorer ce message. Vous conserverez ainsi votre mot de passe actuel </p>

app/views/user_mailler/password_reset.text.erb
 Une demande a &eacute;t&eacute; faite pour r&eacute;initialiser  votre mot de passe. Pour ce faire, cliquez sur le lien ci-dessous

<%= edit_password_reset_url(@user.reset_token, email: @user.email) %>

Ce lien expirera dans deux heures

Si vous n'avez pas solicit&eacute; ce changement de mot de passe, veuillez s'il vous plait, ignorer ce message. Vous conserverez ainsi votre mot de passe actuel