config/routes.rb
Rails.application.routes.draw do
 
  

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'welcome#index'

    get 'signup'  => 'users#new'
    resources :users

    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default main-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Made In Mada", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
         <li><%= link_to "Nos membres", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username.titleize %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Mon compte", current_user %></li>
             <li><%= link_to "Modifier mon compte", edit_user_path(current_user) %></li>
            
            <li></li>
            <li role="separator" class="divider"></li>
            <li><li><%= link_to "Se déconnecter", logout_path, method: :delete %></li></li>
          </ul>
        </li>
        <% else %>
         <li><%= link_to "S'inscrire", signup_path %></li>
         <li><%= link_to "Se connecter", login_path %></li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
</head>
<body>


<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible"><%= message %></div>
<% end %>
<%= yield %>
</body>
</html>